---
title: "Sobre Mim"
about:
    template: jolla
---

Olá! Sou cientista de dados com ampla experiência profissional na área de dados em empresas de diversos portes e setores. Navego entre o mundo dos negócios e dos dados ao criar e implementar modelos, aplicações, agentes e ao comunicar e traduzir insights para diferentes públicos, gerando economias que chegaram a milhões de reais em meus projetos

## Habilidades técnicas
- Banco de Dados Relacional (MySQL e PostgreSQL);

- Linguagens de consulta/programação: SQL avançado, Python avançado (domínio das principais bibliotecas de análise e ciência de dados, aprendizado de máquina e inteligência artificial generativa) e R intermediário;

- Machine Learning: modelos de regressão, classificação e clusterização, incluindo aprendizado supervisionado e não supervisionado, além de modelos de deep learning e de ensemble;

- Gen AI: interface com LLMs, prompt engineering, criação e orquestração de agentes e tasks

- Versionamento de código: Git e GitHub;

- Ambientes em nuvem: AWS (EC2, S3, IAM, Bedrock, Textract e ECS);

- Infraestrutura e deploy: Terraform e Docker básicos

- Ferramentas de BI/Visualização: Power BI (Power Query, M e DAX) e Looker Studio avançados;

- Planilhas: Excel/Google Sheets avançado

## Experiência Profissional

### Cientista de Dados - A3Data: 06/2025 - atualmente:

- Participação como consultor de Ciência de Dados em projetos com clientes de diferentes setores, envolvendo problemas variados de Data Science (classificação, previsão, recomendação), incluindo IA Generativa

- Desenvolvimento de cadências semanais e aprofundamento do relacionamento com o cliente, utilizando metodologia ágil para gerenciamento do projeto

- Análise exploratória dos dados, envolvendo desde importação, limpeza e validação dos dados até análise univariada e multivariada a partir de medidas estatísticas e visualizações de dados

- Realização de engenharia de features de dados qualitativos e quantitativos, incluindo dados temporais cíclicos e criação de features explicativas

- Utilização de modelos avançados de aprendizado de máquina, com foco em métodos de ensemble, como GBMs e Random Forest

- Criação de soluções de Gen AI, abrangendo desde OCR para extração de informações de documentos digitalizados até a criacão de um sistema multi-agente para geração de propostas comerciais

- Avaliação do desempenho de modelos de machine learning e de aplicações de IA generativa, usando métricas apropriadas para o tipo de problema enfrentado

- Análise de Retorno sobre o Investimento da solução, chegando a economia de milhões de reais anuais

- Versionamento de código e colaboração no projeto via Git e GitHub

- Criação de interface web dinâmica e interativa com Streamlit e NiceGUI

- Deployment da solução com uso de AWS EC2/ECS e Docker

<br>

### Cientista de Dados - Intellux: 03/2025 - 05/2025:

- Modelagem de LLMs (Large Language Models), incluindo Llama, Gemma e modelos da OpenAI, para otimização de performance em domínios técnicos específicos, garantindo soluções de IA alinhadas às necessidades do negócio;

- Avaliação contínua da performance de LLMs por meio de métricas e indicadores estratégicos, com foco em qualidade e escalabilidade;

- Análise comparativa entre modelos open-source e closed-source para seleção do modelo fundacional mais adequado, considerando aspectos técnicos e financeiros;

- Criação, manutenção e utilização de scripts, conectando-se a APIs de LLMs usando um servidor remoto para calcular e acompanhar métricas como custo e tempo de resposta;

- Manipulação de dados tabulares, usando bibliotecas como pandas, incluindo a exportação de dados para planilhas Excel para maior facilidade de uso das áreas de negócio

<br>

### Analista de Dados - Conta Simples: 01/2024 - 09/2024:

- Gestão completa de bases de dados, incluindo criação, atualização, limpeza e manutenção, garantindo integridade e qualidade dos dados para análises e tomadas de decisão;

- Desenvolvimento e gerenciamento de relatórios, dashboards e visualizações de dados no Looker Studio, proporcionando insights claros e acionáveis para stakeholders;

- Realização de análises avançadas (diagnósticas, descritivas e preditivas) com aplicação de técnicas estatísticas, como correlação, regressão, modelagem estatística e simulação de cenários, para suporte à estratégia de negócios;

- Automação de processos e fluxos de dados por meio de pipelines e integrações utilizando SQL e Google Sheets, aumentando a eficiência operacional e reduzindo o tempo de entrega de insights;

- Cálculo, monitoramento e análise de KPIs, OKRs e métricas estratégicas, apoiando a tomada de decisões baseadas em dados e o alcance de objetivos organizacionais;

- Liderança técnica em projetos de tecnologia e dados, incluindo a criação de um chatbot integrado ao Slack via APIs e a migração de sistemas com arquiteturas de dados distintas;

- Mapeamento de requisitos de negócio e desenvolvimento de soluções de dados e analytics, desde a concepção até a entrega, alinhando tecnologia às necessidades estratégicas da empresa

## Educação
**ICMC-USP - Bacharelado em Estatística e Ciência de Dados**: 2025 - atualmente  
**FEA-USP - Bacharelado em Administração**: 2020 - 2024

## Certificações
**AWS Certified AI Practitioner**: 2026 - atualmente

